#!/usr/bin/python3
from os import open, close, dup, O_WRONLY, system, getcwd

oldOut = dup(1)
close(1)
open(f"{getcwd()}/.outLogger.txt", O_WRONLY)

oldErr = dup(2)
close(2)
open(f"{getcwd()}/.errLogger.txt", O_WRONLY)

import PySimpleGUI as sg

import mainMenu
import assignments
import reviews

def main():
    """
    The main entry point for the lms GUI application.
    """
    sg.theme("DarkAmber")
    sg.set_options(element_padding=(0, 0))

    openWindow = mainMenu.mainMenuClass()
    status = openWindow.run()

    while status != "Closed":
        if status == "assignments":
            openWindow = assignments.assignmentsMenuClass()
        if status == "reviews":
            openWindow = reviews.reviewsMenuClass()
        if status == "mainMenu":
            openWindow = mainMenu.mainMenuClass()
        status = openWindow.run()


if __name__ == "__main__":
    main()

    close(1)
    dup(oldOut)
    close(oldOut)

    close(2)
    dup(oldErr)
    close(oldErr)
