#!/usr/bin/python3
import PySimpleGUI as sg

import mainMenu
import core


def main():
    """
    The main entry point for the lms GUI application.
    """
    sg.theme("DarkAmber")
    sg.set_options(element_padding=(0, 0))

    mainMenuObj = mainMenu.mainMenuClass()
    mainMenuObj.run()


if __name__ == "__main__":
    main()
