name: Generate Exacutable

on:
  push:
    tags:
    - v*

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]


    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pyinstaller PySimpleGUI custom-inherit tk
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build Exacutables
      run: pyinstaller --onefile --windowed lms --name wtc-lms-GUI

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/wtc-lms-GUI
